### ISSUE TITLE
Problems after selecting AllowFlyerSpeedLeveling

### ISSUE THREAD

**Issue by MightBeHarmless** [cadon/ARKStatsExtractor#1179]
Playing on a non-modded private server with Flyer Speed Leveling enabled.
When I noticed that you have augmented this app to support this, I checked the appropriate box under Settings.
The program still failed to recognize the "Last Export" which has two points (post-tame) in speed.
I abandoned the import, exited and relaunched ASB.
Now, each time I try to open this save file, I get this message in a .NET popup dialog.
Even when I attempt to clear AllowFlyerSpeedLeveling and load the saved DB from disk, the error persists.
Luckily we may press "Continue" to proceed, but I don't trust the stability of the engine after this point, so stopped using it.

Thank you for adding this feature into ASB.

```text
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ARKBreedingStats.multiplierTesting.StatsMultiplierTesting.CbAllowFlyerSpeedLeveling_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.set_Checked(Boolean value)
   at ARKBreedingStats.multiplierTesting.StatsMultiplierTesting.SetStatMultipliersFromCC()
   at ARKBreedingStats.multiplierTesting.StatsMultiplierTesting.set_CreatureCollection(CreatureCollection value)
   at ARKBreedingStats.Form1.InitializeCollection(Boolean keepCurrentSelection)
   at ARKBreedingStats.Form1.LoadCollectionFile(String filePath, Boolean keepCurrentCreatures, Boolean keepCurrentSelections)
   at ARKBreedingStats.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by MightBeHarmless** [comment]
My save file is using "FormatVersion":"1.13"

When I clear the checkbox and save settings followed by relaunching the application, I don't receive this error with any of three data files that I tested with.

When I set the checkbox and immediately save settings followed by relaunching the application, only the one save file I was working with at the time I made the change cause this error message to occur. The error will pop up every time I open that save file, or relaunch the application after that was the last save file in use.

**Comment by cadon** [comment]
Hi, sorry for that inconvenience. That setting is not yet supported, it first needs a new values.json file with a new format. I added the checkbox already to be ready for that. Unfortunately there's an exception if that checkbox is enabled that you experienced. That exception will be fixed in the next release and the new values file will be ready in the next few days.

**Comment by coldino** [comment]
This issue is resolved since flyer speed levelling is now fully supported.

**Comment by MightBeHarmless** [comment]
Thank you!
