### ISSUE TITLE
Unhandled exception extracting imprinting bonus with pteranadons

### ISSUE THREAD

**Issue by Twanfox** [cadon/ARKStatsExtractor#130]
Actual exception below. 

Exception occurs on the following line:
numericUpDownImprintingBonusExtractor.Value = (decimal)Extraction.E.imprintingBonus * 100;

It appears the imprinting bonus control on the Extractor is being updated with a new value, which exceeds the upper bounds (100) defined in the control. Adjusting this in my own debug version allows the code to complete, but fails extraction on all except Sta and Oxy.

My unofficial server uses adjusted cuddle time and state increase values (2.0 stat, 0.4 cuddle).
Pteranadon stats: Level 124, HP 1186.9, Sta 750, Oxy 495, Food 4828, Wght 250.3, Dmg 343, Spd 169.6, Torp 1353.6, Imprint bonus 86%, fully matured.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '134.99831252109300' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at ARKBreedingStats.Form1.extractLevels()
   at ARKBreedingStats.Form1.buttonExtract_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cadon** [comment]
Hi, thanks for the feedback. I fixed the bug with the upper-bound. For the CuddleIntervall there's a setting, try to set it in v0.20.8.3, maybe that solves the issues.

**Comment by cadon** [comment]
With the settings (2.0 stat, 0.4 cuddle) it now works, I could extract the levels of the Ptera.
