### ISSUE TITLE
Crash Error While Importing

### ISSUE THREAD

**Issue by Worldgate** [cadon/ARKStatsExtractor#1317]
Tried to import one of the saves and i get this.

Save file import error - ARK Smart Breeding v0.56.2.0

An error occurred while importing the file E:\Extinction.ark.

One or more errors occurred.

System.AggregateException in mscorlib

Method throwing the error: System.Threading.Tasks.Task.ThrowIfExceptional

StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SavegameToolkit.ArkSavegame.readBinaryStoredObjects(ArkArchive archive, ReadingOptions options)
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options)
   at ARKBreedingStats.ImportSavegame.ReadSavegameFile(String fileName)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.ImportSavegame.<ImportCollectionFromSavegame>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.Form1.<RunSavegameImport>d__677.MoveNext()

Inner Exception:
Object reference not set to an instance of an object.

**Comment by cadon** [comment]
Hi, can you send me the save file zipped for further investigation (upload here or send via discord)? Looks like the new cryopod save format has unknown properties not correctly handled.

**Comment by Worldgate** [comment]
one sec

**Comment by cadon** [comment]
The issue is fixed and will be in the next release. It was related to Fjordhawks having inventory components of their owners, unlike (all?) other species.
