### ISSUE TITLE
Import Save Game produces error

### ISSUE THREAD

**Issue by eddielane71488** [cadon/ARKStatsExtractor#1323]
When attempting to import my server save I get the following error. 

Save file import error - ARK Smart Breeding v0.58.0.0

An error occurred while importing the file Z:\ASA\ShooterGame\Saved\SavedArks\TheIsland_WP\TheIsland_WP.ark.

Found unknown Version 20819

System.NotSupportedException in SavegameToolkit

Method throwing the error: SavegameToolkit.ArkSavegame.readBinaryHeader

StackTrace:
   at SavegameToolkit.ArkSavegame.readBinaryHeader(ArkArchive archive)
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options)
   at ARKBreedingStats.ImportSavegame.ReadSavegameFile(String fileName)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.ImportSavegame.<ImportCollectionFromSavegame>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.Form1.<RunSavegameImport>d__699.MoveNext()

**Comment by cadon** [comment]
The file format for ASA is completely different from the format of ASE and is currently not supported.
