### ISSUE TITLE
Save file import error - ARK Smart Breeding v0.60.4.0

### ISSUE THREAD

**Issue by shenniko** [cadon/ARKStatsExtractor#1349]
Error when trying to import save file:

Save file import error - ARK Smart Breeding v0.60.4.0

An error occurred while importing the file E:\SteamLibrary\steamapps\common\ARK Survival Ascended Dedicated Server\ShooterGame\Saved\SavedArks\TheIsland_WP\TheIsland_WP.ark.

Found unknown Version 20819

System.NotSupportedException in SavegameToolkit

Method throwing the error: SavegameToolkit.ArkSavegame.readBinaryHeader

StackTrace:
   at SavegameToolkit.ArkSavegame.readBinaryHeader(ArkArchive archive)
   at SavegameToolkit.ArkSavegame.ReadBinary(ArkArchive archive, ReadingOptions options)
   at ARKBreedingStats.ImportSavegame.ReadSavegameFile(String fileName)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.ImportSavegame.<ImportCollectionFromSavegame>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ARKBreedingStats.Form1.<RunSavegameImport>d__754.MoveNext()

**Comment by Olfi01** [comment]
@cadon Would you be interested in a PR using [ark-save-parser](https://github.com/VincentHenauGithub/ark-save-parser) via [Python.NET](https://github.com/pythonnet/pythonnet) to read ASA save files?

**Comment by cadon** [comment]
Hi, sounds great!
Currently there are some bigger changes regarding the layout, but if the changes are mainly restricted to the file ARKBreedingStats/ImportSavegame.cs there should be no issue. Regarding the licenses it looks fine.

**Comment by coldino** [comment]
> @cadon Would you be interested in a PR using [ark-save-parser](https://github.com/VincentHenauGithub/ark-save-parser) via [Python.NET](https://github.com/pythonnet/pythonnet) to read ASA save files?

You might want to hold off on this for a moment as @flintthatchwood was recently close to completing the C# save reader. We've even had to update away from the old .Net framework versions to accommodate it, which has been quite a task. I wonder if we can get an update on the current state?
