### ISSUE TITLE
Exception thrown when OCR is used (1680x1050)

### ISSUE THREAD

**Issue by Dessa** [cadon/ARKStatsExtractor#160]
i can 100 % reproduce that, it used to work with an older version, though i'm using 1680x1050 but even though "it is not working well" its already a huge time-saver

it doesn't seem to affect the functionality, since after the error message the values are actually being passed and i just have to press enter

i have VS installed so here is the exception detail:
```
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=ARK Smart Breeding
  StackTrace:
       at ARKBreedingStats.Form1.doOCR(String imageFilePath, Boolean manuallyTriggered) in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Form1.cs:line 2810
       at ARKBreedingStats.Form1.btnReadValuesFromArk_Click(Object sender, EventArgs e) in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Form1.cs:line 3154
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at ARKBreedingStats.Program.Main() in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Program.cs:line 22
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by cadon** [comment]
Thanks, found the bug, will be fixed in the next release. The tool tries to read the imprinting-percentage as well, but as the text is in a smaller font, the match is not very good, even for the 1920-res, and I haven't included it in the 1680 yet. That caused the outofIndex-issue.

**Comment by cadon** [comment]
Hi, that should be resolved now (0.20.11.1). Can you check if the error is not happening anymore?

**Comment by Dessa** [comment]
the trace changed slightly

```
System.IndexOutOfRangeException was unhandled
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=ARK Smart Breeding
  StackTrace:
       at ARKBreedingStats.Form1.determineDinoRaceFromStats(Single[] stats, String name) in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Form1.cs:line 2900
       at ARKBreedingStats.Form1.doOCR(String imageFilePath, Boolean manuallyTriggered) in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Form1.cs:line 2835
       at ARKBreedingStats.Form1.btnReadValuesFromArk_Click(Object sender, EventArgs e) in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Form1.cs:line 3176
       at System.Windows.Forms.Control.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnClick(EventArgs e)
       at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Button.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at ARKBreedingStats.Program.Main() in P:\dev\src\ARKStatsExtractor\ARKBreedingStats\Program.cs:line 22
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by cadon** [comment]
Thanks for the report, I missed that, it'll be fixed in the next release.

**Comment by cadon** [comment]
It's released, next try :)

**Comment by Dessa** [comment]
that worked, thanks!
