### ISSUE TITLE
Tried to filter the server and it threw an error and no wont ASB won't load

### ISSUE THREAD

**Issue by cyberangel67** [cadon/ARKStatsExtractor#675]
As the title says, error attached.

Now the question is what file do I need to edit to make it show all servers in the library again, to bypass this issue in failing to load up?
![capture](https://user-images.githubusercontent.com/1366816/39566232-440effd0-4efe-11e8-9514-d81d3d55683f.PNG)

**Comment by cadon** [comment]
Hi, can you click on "Details" and post the text that appears?

**Comment by cyberangel67** [comment]
Yep, pasted below.

Btw, I think this was due to me clicking on the col0 column in the library as that is where I first saw the error.

Anyway as requested

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '20' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListViewItem.ListViewSubItemCollection.get_Item(Int32 index)
   at ListViewColumnSorter.Compare(Object x, Object y)
   at System.Windows.Forms.ListView.CompareFunc(IntPtr lparam1, IntPtr lparam2, IntPtr lparamSort)
   at System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by cyberangel67** [comment]
ok on further testing,it has to do with importing from the actual server save.

I managed to open it up, by clicking on continue a hundred or so times and then created a new library. I then did the run and import and it is throwing the error a hundred or so times.

**Comment by cyberangel67** [comment]
it also appears to not also import all the dinos either, I have found my sarcos and rex's haven't been imported. There is probably more, but they are the two that stick out.

**Comment by cadon** [comment]
Thanks, I think I found the bug. It can happen if you have disabled the color-columns in the library in the general settings. It'll be fixed in the next release. For now you can enable the setting that shows the color-columns.
