### ISSUE TITLE
Null-Exception when importing-last-exported

### ISSUE THREAD

**Issue by purevet** [cadon/ARKStatsExtractor#728]
Latest version does this to me when attempting to import stats.

Unhandled exception has occurred in your application. If you click continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Object reference not set to an instance of an object.

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
at ARKBreedingStats.SpeciesSelector.setSpecies(String species)
at ARKBreedingStats.Form1.setCreatureValuesToExtractor(CreatureValues cv)
at ARKBreedingStats.Form1.extractExportedFileInExtractor(String exportFile)
at ARKBreedingStats.Form1.importLastExportedCreature()
at ARKBreedingStats.Form1.btImportLastExported_Click(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by VolatilePulse** [comment]
Per a discussion on the Discord channel, this is not an issue when using "Import Exported Data", but rather when using the "Last Export" feature. While this is a more favorable feature, it is recommended to address the "Last Export" feature.

There appears to be an issue matching up the Species from the Export file and the Species list by use of the "ARKBreedingStats.SpeciesSelector.setSpecies(String species)" method.

**Comment by cadon** [comment]
An exported file that causes this issue would be helpful for fixing this bug.
